markdown: kramdown
highlighter: rouge
permalink: /blog/:title
conference-name: "Better Software"
conference-title: "Green Software"
conference-motto: "La conferenza per chi sviluppa software sostenibile e costruisce un futuro tecnologico migliore."
conference-domain: "bettersoftware.it"
conference-email: bettersoftware@grusp.org
conference-x: better_software
city: "Bologna"
date: "11 Ott"
year: 2024
tickets: false
tickets-eb: //eventbrite.com/tickets-external?eid=49969466018&ref=etckt
tickets-eb-link: http://kerning-2019.eventbrite.com
tickets-eb-height: 950px
speakers: false
talks: false
workshops: false
schedule: false
sponsor: false
location-stay: false
cfs: false
rdiscount:
  extensions: [smart]
plugins:
  - jekyll-sitemap
kramdown:
  input: GFM
