markdown: kramdown
highlighter: rouge
permalink: /blog/:title
conference-name: "Better Software"
conference-title: "Green Software"
conference-motto: "La conferenza più eclettica sul mondo IT!"
conference-domain: "bettersoftware.it"
conference-email: bettersoftware@grusp.org
conference-x: better_software
city: "Bologna"
date: "11 Ott"
year: 2024
tickets: true
tickets-eb: grusp/bettersoftware-2024
tickets-eb-link: http://ti.to/grusp/bettersoftware-2024
tickets-eb-height: 950px
speakers: false
talks: false
workshops: false
schedule: false
sponsor: false
location-stay: false
cfs: true
rdiscount:
  extensions: [smart]
plugins:
  - jekyll-sitemap
kramdown:
  input: GFM
